version: '2'

services:
   grafana-server:
      build: ./docker/grafana
      container_name: grafana-server
      mem_limit: 256M
      ports:
      - 3000:3000
   
   prometheus-server:
      build: ./docker/prometheus
      container_name: prometheus-server
      mem_limit: 256M
      ports:
      - 9091:9090

   zookeeper:
       image: confluentinc/cp-zookeeper:5.2.1
       environment:
         ZOOKEEPER_CLIENT_PORT: 2181
         ZOOKEEPER_TICK_TIME: 2000
         ZOOKEEPER_SYNC_LIMIT: 2

   kafka:
       image: confluentinc/cp-kafka:5.2.1
       ports:
         - "9092:9092"
       depends_on:
         - zookeeper
       environment:
         KAFKA_BROKER_ID: 1
         KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
         KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
         KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
         KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"


